version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "19:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: chai
    versions:
    - 4.2.0
    - 4.3.0
    - 4.3.3
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: async
    versions:
    - 3.2.0
  - dependency-name: lodash
    versions:
    - 4.17.20
